### ISSUE TITLE
Cargo-concordium: output to `concordium-out/module.wasm.v1` by default

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-smart-contract-tools#155]
**Description**
Cargo concordium should output the wasm module to `PROJECT_ROOT/concordium-out/module.wasm.v1` by default, as it is cumbersome and error-prone to write manually all the time. Where `PROJECT_ROOT` is the folder with the manifest file (`Cargo.toml`).
All of our example contracts with integration tests require this location anyhow and we also recommend it in our developer documentation.

The only downside is that it is a breaking change.

**Comment by abizjak** [comment]
I don't think it should be `./...`. cargo-concordium can be run from other places, e.g., inside src directory.

If anything it should be relative to the location of the manifest file.

**Comment by Bargsteen** [comment]
Good point. I've amended the description.
