### ISSUE TITLE
Release cargo concordium with protocol 7 support

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-smart-contract-tools#164]
The reduced execution costs should be integrated into cargo concordium and released.

**Comment by limemloh** [comment]
This work depends on [https://github.com/Concordium/concordium-rust-sdk/issues/192](https://github.com/Concordium/concordium-rust-sdk/issues/192) being done

**Comment by soerenbf** [comment]
This was a misunderstanding, as it references concordium-base as a sub-module.
