### ISSUE TITLE
Cargo-concordium: embed schema by default

### ISSUE THREAD

**Issue by lassemoldrup** [Concordium/concordium-smart-contract-tools#173]
**Description**
We should consider having `cargo-concordium` embed the schema by default when building smart contracts, since it is most often what you want. If we do this, we need to add a flag for opting out. This could be `--no-schema-embed`/`-n`. Maybe it is worth keeping the existing `--schema-embed`/`-e` flag as a (deprecated) no-op to not break people's working build commands?

**Comment by limemloh** [comment]
I agree, we should keep the `--schema-embed` but show a warning when people use it
