### ISSUE TITLE
VSCode ext: Show error message when setting invalid custom cargo-concordium binary

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-smart-contract-tools#64]
**Description**

In the VSCode extension, it is possible to set a custom binary path to cargo concordium.
Issues with the binary, fx that it is missing or isn't executable, isn't displayed to the user.

**Steps to Reproduce**
1. Set the custom cargo path to a non-existing file or to a non-executable cargo concordium
2. Run the contract build command

**Expected Result**
A popup stating that the binary is missing or not executable.

**Actual Result**
Nothing.

**Note**
A popup with a useful error message *is* displayed when using the cargo concordium version command.
We should match that behavior for the other commands.

**Versions**
- Software Version: 0.1.0-0
- OS: macOS Ventura (Apple M2)

**Comment by limemloh** [comment]
Fixed as part of #58
