### ISSUE TITLE
It is not available for Mac with Silicon chips. 

### ISSUE THREAD

**Issue by bogacyigitbasi** [Concordium/concordium-smart-contract-tools#68]
<img width="1427" alt="Screenshot 2023-05-01 at 14 47 04" src="https://user-images.githubusercontent.com/110228281/235448262-7b063696-9e62-4c9b-baa3-8924ab000f2c.png">
**Bug Description**
The 'Concordium Smart Contracts' extension is not available in Visual Studio Code for Mac Silicon.

May worth look into this for potential fixes: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions

**Versions**
Apple MacBook Air M1
OS: Ventura 13.2.1

**Comment by limemloh** [comment]
I have published a build of the extension targeting `darwin-arm64`, fixing this.
