### ISSUE TITLE
VSCode Extension doesn't show an error if 'it doesn't know' what contract to build

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-smart-contract-tools#69]
**To reproduce:**

1. Initialize the contract from the template.
2. Create a folder when the VSCode asks to select one.
3. Select the folder you have just created.
3. Don't open the lib.rs file, try the build command.

**Result:**
First time, there is an error shown that folder where the contract exists doesn't exist.
Second time, it just doesn't show any errors.

**Expected**
Error that would explain the user to select contract to build.

**Version**
1.0.1

**Comment by abizjak** [comment]
@limemloh Is this still an issue? YOu changed some error handling not too long ago?

**Comment by mh-concordium** [comment]
I have just added version now, I found it in 1.0.1.

**Comment by limemloh** [comment]
Yes, it is still an issue.
It also seems that vscode is not even running the command in this case, since the command is registered as a text editor command, since this is how it determines where to run cargo-concordium build from.
A fix is to hide the build command when no text editor is focused.

**Comment by limemloh** [comment]
Fix by #72
