### ISSUE TITLE
Automatically (re)compile module for integration tests

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-smart-contract-tools#83]
**Task description**

The testing library uses compiled smart contract modules for testing. This means that users must use `cargo concordium build` to build the module before the tests can run.
It also means that you must recompile your smart contract every time you make changes, otherwise, the tests will run against the "old code".
This task is about removing the need for manual compilation, which will also remove the risk of testing the incorrect, old, code.

**Comment by abizjak** [comment]
Can you please elaborate the description of this task please.
